[package]
name = "ledc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ctrlc = "3.2.2"
eframe = "0.19.0"
serialport = "4.2.0"
